site_name: config
site_description: News backend for Bobotog'
repo_url: https://github.com/sevbo2003/bobotog-news
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/sevbo2003">sevbo2003</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
